services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "80:4533" # Navidrome default HTTP port
    volumes:
      - ./data:/data # Persistent data storage
      - ./music:/music # Your music library
    environment:
      - ND_LOGLEVEL=info
      - ND_SESSIONTIMEOUT=24h
      - ND_SCANSCHEDULE=1h
      # Add more Navidrome environment variables as needed
    restart: unless-stopped
